### ISSUE TITLE
Dependency on thingatpt+ has broken package installation

### ISSUE THREAD

**Issue by NateEag** [ninrod/exato#1]
As you may have seen in this issue, EmacsWiki packages are no longer available on MELPA:

https://github.com/melpa/melpa/pull/5008#issuecomment-360501258

Due to exato's dependency on `thingatpt+.el` (one of the now-gone EmacsWiki packages), it can no longer be installed via MELPA.

To reproduce:

    $ emacs -Q

then eval the following code:

```elisp
(require 'package)
(add-to-list 'package-archives '("melpa" .
                                 "http://melpa.milkbox.net/packages/"))
(package-initialize)
```

then run `M-x list-packages` and try to install `exato`.

Instead of installing, the minibuffer shows the error `Package 'thingatpt+-0' is unavailable`.

**Comment by ninrod** [comment]
Very interesting. thanks for mentioning it. I'll have to see what I can do from here.

**Comment by ninrod** [comment]
@NateEag, should be fixed now. Thank you!

**Comment by ninrod** [comment]
I've just pushed the changes so you'll have to wait until the next melpa build, which should kick in in a few hours.

**Comment by NateEag** [comment]
Works for me. Thank you!
